convoy-volume-agent-longhorn:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /var/run:/host/var/run
    - /etc/docker/plugins:/etc/docker/plugins
  image: cjellick/convoy-agent:longhorn-2
  command:
  - volume-agent-longhorn

convoy-volume-driver-longhorn:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.container.agent.role: 'environment'
    io.rancher.scheduler.global: 'true'
  privileged: true
  pid: host
  volumes:
    - /lib/modules:/lib/modules:ro
    - /proc:/host/proc
    - /dev:/host/dev
    - /var/run:/host/var/run
    - /etc/docker/plugins:/etc/docker/plugins
  image: cjellick/convoy-agent:longhorn-2
  command:
  - volume-driver-longhorn

convoy-longhorn-storagepool:
  labels:
    io.rancher.container.create_agent: 'true'
  image: cjellick/convoy-agent:longhorn-2
  volumes:
    - /var/run:/host/var/run
  command: storagepool-agent
